(function () {
  const BASE_PROMPTS = [
    "A professional commercial portrait of a man walking down a modern luxury hotel hallway wearing a red blazer, white dress shirt, black trousers, and dress shoes, captured in a clean vertical 9:16 aspect ratio.",
    "An outdoor adventure portrait of a man standing on a grassy mountain ridge above a sea of clouds wearing a blue hooded jacket, black pants, cap, and hiking boots, shot in vertical 9:16 layout.",
    "A morning sunrise mountain portrait of a man standing on a grassy hill above cloud layers wearing a dark jacket and shorts, vertical 9:16 aspect ratio.",
    "A tropical beach lifestyle portrait of a man walking barefoot along the shoreline at sunset wearing a blue denim shirt and cuffed jeans, vertical 9:16 layout.",
    "A dramatic sunrise mountain summit portrait of a man holding a coffee thermos above rolling clouds wearing a black puffer jacket and burgundy pants, vertical 9:16 aspect ratio.",
    "A urban cafe portrait of a man sitting outdoors wearing sunglasses, a black jacket, and white t-shirt holding a coffee cup, vertical 9:16 layout.",
    "A high-angle rooftop portrait of a man seated on a skyscraper ledge holding a camera over a glowing city skyline at dusk wearing a dark long-sleeve and ripped jeans, vertical 9:16 layout.",
    "A cinematic moody portrait of a man in a white suit and sunglasses sitting on a chair holding a coffee cup in a dark studio setting, vertical 9:16 aspect ratio.",
    "An urban night portrait of a man walking through a vibrant Japanese street market with glowing red lanterns wearing a tan shirt over a black t-shirt and grey jeans, vertical 9:16 layout.",
    "An executive portrait of a man sitting crossed-legged in a blue armchair inside a modern high-rise office at night wearing a grey suit, vertical 9:16 aspect ratio.",
    "An action conceptual photo of a man floating in mid-air amidst a dramatic tornado debris storm wearing a white t-shirt and ripped jeans, vertical 9:16 layout.",
    "A travel portrait of a man standing at a modern train station platform with a black suitcase next to a high-speed train wearing a brown shirt and cargo pants, vertical 9:16 layout.",
    "An airport runway portrait of a man posing with a grey suitcase in front of an Emirates airplane wearing a blue shirt and white pants, vertical 9:16 aspect ratio.",
    "An moody indoor portrait of a man sitting in an executive chair looking out a large window wearing a beige suit, vertical 9:16 layout.",
    "A formal portrait of a man standing in a modern studio wearing a white suit with a black bow tie beside abstract wall art, vertical 9:16 aspect ratio.",
    "A scenic travel portrait of a man standing by Lake Kawaguchiko with Mount Fuji and cherry blossoms in the background wearing a brown coat and scarf, vertical 9:16 layout.",
    "A minimalist studio portrait of a man sitting crossed-legged on a metal chair wearing a cream suit against a warm beige background, vertical 9:16 aspect ratio.",
    "An urban street style portrait of a man standing outdoors wearing a black Adidas hoodie with white stripes, grey cargo pants, sunglasses, and black sneakers, vertical 9:16 layout.",
    "A city night portrait of a man standing on a modern illuminated pedestrian bridge wearing a denim jacket, black graphic tee, and light denim jeans, vertical 9:16 layout.",
    "A nature photography portrait of a man taking a photo with a camera on a wooden bridge in front of a waterfall wearing a dark jacket and backpack, vertical 9:16 aspect ratio.",
    "A travel portrait of a man standing in Piazza San Marco in Venice surrounded by pigeons with the St Mark's Campanile in the background wearing a blue polo shirt and beige pants, vertical 9:16 layout.",
    "A scenic sunset portrait of a man standing on a stone embankment by the river in Florence near Ponte Vecchio wearing a light blue shirt and navy trousers, vertical 9:16 layout.",
    "An architectural travel portrait of a man standing in front of Milan Cathedral (Duomo di Milano) surrounded by pigeons wearing a grey bomber jacket, white shirt, and black jeans, vertical 9:16 aspect ratio.",
    "A countryside landscape portrait of a man standing in a Tuscan vineyard with rolling green hills at golden hour wearing a tan sweater and beige pants, vertical 9:16 layout.",
    "A coast lifestyle portrait of a man standing on a hill in Positano Amalfi Coast holding sunglasses wearing a white linen shirt and light blue shorts, vertical 9:16 aspect ratio.",
    "A campus lifestyle portrait of a man standing outdoors holding a DSLR camera in front of POLBAN university buildings wearing a tan jacket and light jeans, vertical 9:16 layout.",
    "A cozy cafe portrait of a man sitting by a window holding a coffee cup with a vintage camera on the wooden table wearing a dark blazer, vertical 9:16 aspect ratio.",
    "A barber shop mirror selfie portrait of a man sitting in a barber chair taking a photo with a smartphone wearing a grey jacket, white t-shirt, sunglasses, and white sneakers, vertical 9:16 layout.",
    "A shopping mall lifestyle portrait of a man walking along a glass balcony wearing a white fleece jacket, black t-shirt, beige cargo pants, and white sneakers, vertical 9:16 layout.",
    "A fine dining restaurant portrait of a man sitting crossed-legged at a dining table wearing a coral long-sleeve sweater, white pants, and brown leather shoes, vertical 9:16 aspect ratio.",
    "A outdoor nature portrait of a man leaning on a white wooden fence in a green forest wearing a dark grey long-sleeve shirt and black pants, vertical 9:16 layout.",
    "A Hollywood Walk of Fame portrait of a man crouching next to a celebrity star bearing the text \"RYZALMS\" wearing a black tuxedo with a bow tie, vertical 9:16 layout.",
    "A studio editorial portrait of a man leaning on a glass table wearing a black leather jacket against a grey studio background, vertical 9:16 aspect ratio.",
    "A warm rustic cafe portrait of a man sitting at a wooden table smiling, wearing a tan corduroy jacket over a white turtleneck sweater, vertical 9:16 layout.",
    "A modern work lifestyle portrait of a man working on a laptop at a cafe table with a cup of coffee wearing a dark suit jacket and white shirt, vertical 9:16 aspect ratio.",
    "A surreal dynamic splash portrait of a man running forward surrounded by explosive mint-green liquid splashes wearing a matching mint hoodie and sweatpants, vertical 9:16 layout.",
    "A cozy evening cafe portrait of a man sitting at a wooden table with arms crossed wearing a tan knit cardigan sweater over a white t-shirt, vertical 9:16 layout.",
    "A minimalist fashion studio portrait of a man sitting on the floor leaning back against a soft pink backdrop wearing a white crewneck sweater and white pants, vertical 9:16 layout.",
    "A close-up indoor portrait of a man resting his head on his hand at a cafe table wearing a black denim jacket over a white t-shirt and smartwatch, vertical 9:16 layout.",
    "An aesthetic indoor portrait of a man sitting on the floor leaning against a white wall with natural light shadows wearing a dusty pink denim jacket, white shirt, and white pants, vertical 9:16 layout.",
    "An outdoor garden portrait of a man leaning on a metal staircase handrail wearing a light sage quarter-zip sweater, white pants, and round sunglasses, vertical 9:16 layout.",
    "A commercial brand portrait of a man leaning against a giant red Coca-Cola can wearing a red bomber jacket, white shirt, black jeans, and red sneakers, vertical 9:16 layout.",
    "A cowboy countryside portrait of a man riding a brown horse in an open field wearing a cowboy hat, denim shirt, sunglasses, and leather gloves, vertical 9:16 aspect ratio.",
    "A surreal creative conceptual portrait of a man sitting inside a giant realistic blue eyeball iris wearing a blue shirt, cap, and orange sling bag, vertical 9:16 layout.",
    "A safari wildlife photography portrait of a man lying in tall grass taking a photo with a long lens camera while a large male lion stands directly behind him, vertical 9:16 layout.",
    "A futuristic creator portrait set in a studio filled with holographic mathematical formulas with a man in a dark grey linen jacket and black shirt, vertical 9:16 aspect ratio. In the top corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A low-angle portrait of an architect inside a skyscraper atrium filled with quantum physics equations wearing a charcoal blazer and white shirt, vertical 9:16 layout.",
    "A commercial lab portrait surrounded by mathematical diagrams and blue holographic displays with a man in a white button-down shirt on a table edge, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "An editorial portrait of a creative director in front of a floor-to-ceiling sunset window with floating glowing code wearing a beige suede jacket, vertical 9:16 layout.",
    "A high-end studio portrait with physics formulas and AI graphics swirling around a man sitting in a chrome chair wearing a light olive suit, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "A high-fashion minimalist studio portrait with long geometric shadows featuring a man in an olive-green blazer, white t-shirt, and grey trousers, vertical 9:16 layout. In the top corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A moody rooftop portrait at dusk with city lights bokeh featuring a man in a black leather jacket leaning against a glass railing, vertical 9:16 aspect ratio.",
    "A warm library portrait with dark oak shelves featuring a man sitting in a leather chair with espresso wearing a cream turtleneck, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "A luxury yacht deck portrait under clear skies featuring a man in a light pink linen shirt, white shorts, and aviator sunglasses, vertical 9:16 aspect ratio.",
    "A high-gloss beauty portrait against a dark charcoal backdrop with side lighting featuring a man in a burgundy suit jacket and black silk shirt, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "An ultra-luxurious penthouse portrait overlooking a night skyline with a man in a custom midnight blue tuxedo and black bow tie, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A street style portrait in an urban plaza with steel architecture featuring a man in a sand-beige trench coat over a black hoodie, vertical 9:16 aspect ratio.",
    "A golden hour infinity pool portrait overlooking the ocean featuring a man leaning on the pool edge wearing a light-teal resort shirt, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "An industrial loft portrait with red brick walls featuring a man sitting on a barstool holding an acoustic guitar wearing a dark green suede jacket, vertical 9:16 layout.",
    "A fantasy studio portrait with floating golden dust particles featuring a man in an embroidered white velvet jacket with gold trim, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "An art gallery commercial portrait with white walls featuring a man in a terracotta suit jacket and black turtleneck sweater, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "An outdoor pine forest mist portrait with sunbeams featuring a man in a khaki canvas jacket, black thermal, and hiking boots, vertical 9:16 layout.",
    "A rooftop lounge portrait with mahogany interiors featuring a man leaning against a marble bar counter wearing a slate-blue suit jacket, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "An urban street portrait with blooming jacaranda trees featuring a man walking with coffee wearing a yellow knit sweater and light jeans, vertical 9:16 layout.",
    "A surreal fashion shot against an emerald backdrop with iridescent bubbles featuring a man in an emerald-green velvet blazer, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "An architectural conservatory portrait with indoor palms featuring a man in a light tan double-breasted suit jacket and linen shirt, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A neon-lit city bridge portrait under rain featuring a man in a dark trench coat over a charcoal hoodie looking over his shoulder, vertical 9:16 aspect ratio.",
    "A golden-hour deck portrait overlooking a vineyard featuring a man in a burnt-orange suede bomber jacket and off-white shirt, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "A gallery portrait with geometric shadows featuring a man standing in an asymmetrical slate-grey blazer and white sneakers, vertical 9:16 layout.",
    "A mystical portrait with golden embers and smoke featuring a man in a navy velvet jacket with silver embroidery, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "A minimalist photo studio portrait with gradient lighting featuring a man in an off-white tailored jacket and linen t-shirt, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A coastal sunset portrait on rocky terrain with ocean mist featuring a man in a dark navy wool overcoat and charcoal sweater, vertical 9:16 layout.",
    "A hotel lobby portrait with crystal chandeliers featuring a man in a light grey suit jacket, white shirt, and navy trousers, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "An urban street fashion portrait in a boutique district featuring a man in an olive green utility jacket walking with a smartphone, vertical 9:16 aspect ratio.",
    "A fantasy portrait with floating flower petals and dust sparkles featuring a man in a lavender knit sweater against a dark plum backdrop, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "An executive skyscraper atrium portrait featuring a man in a bespoke royal blue suit jacket and open-collar white shirt, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A twilight highway portrait beside a vintage sports car featuring a man in a dark brown leather bomber jacket, vertical 9:16 layout.",
    "A Scandinavian living room portrait with a fireplace featuring a man sitting on a cream sofa holding a mug wearing a forest-green wool sweater, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "A street fashion portrait against a concrete mural wall featuring a man in an oversized pastel blue denim jacket, vertical 9:16 layout.",
    "An enchanting portrait with golden bokeh lights featuring a man in a maroon velvet blazer leaning against a dark pillar, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "A minimalist studio portrait with warm-grey stone backdrops featuring a man in a tailored charcoal blazer and white shirt, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A misty mountain sunrise portrait with golden rays piercing fog featuring a man in a dark navy padded vest, vertical 9:16 layout.",
    "A executive lounge portrait with skyline lights featuring a man sitting on a leather sofa in a beige double-breasted jacket, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "A European alleyway portrait with vintage brick facades featuring a man walking in an unbuttoned sage-green linen shirt, vertical 9:16 layout.",
    "A black backdrop studio shot with golden sparkling particles featuring a man in a rich plum velvet jacket, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "A luxury office suite portrait featuring a man standing in a navy blue blazer with hands in his pockets, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A mountain summit sunset portrait under pink clouds featuring a man in a black windbreaker jacket, vertical 9:16 layout.",
    "A terracotta wall studio portrait featuring a man sitting on a wooden bench in an ivory knit sweater, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "A shopping district portrait featuring a man walking in a light olive denim jacket and beige trousers, vertical 9:16 aspect ratio.",
    "A blue backdrop studio shot with floating golden sparkles featuring a man sitting in an emerald suit jacket, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "A museum corridor portrait with white arches featuring a man walking in a tan double-breasted suit jacket, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A black sand beach sunset portrait with ocean waves featuring a man in a dark olive green wool coat, vertical 9:16 aspect ratio.",
    "A penthouse library portrait with mahogany shelves featuring a man in a light grey cashmere sweater with a coffee cup, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "A city plaza portrait with glass skyscrapers featuring a man walking in a dark blue denim jacket, vertical 9:16 aspect ratio.",
    "An indigo backdrop portrait with iridescent bubbles featuring a man on a chrome stool wearing a burgundy velvet blazer, vertical 9:16 layout. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "A corporate boardroom portrait with panoramic city views featuring a man standing in a charcoal grey suit jacket, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"TIGAJIWA\".",
    "A tropical boardwalk portrait at sunrise featuring a man in a light blue linen shirt and cream shorts, vertical 9:16 layout.",
    "A travertine stone wall studio portrait featuring a man sitting in a terracotta knit sweater, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"SAHABATKAYA\".",
    "An art plaza portrait with steel structures featuring a man walking in a sage green jacket, vertical 9:16 layout.",
    "A black studio shot with floating golden dust particles featuring a man standing in a maroon velvet suit jacket, vertical 9:16 aspect ratio. In the corner, a subtle branding watermark reads \"MIKROMISTIK\".",
    "A hyperrealistic cinematic portrait of a modern CEO standing confidently in a luxury urban studio, soft natural key lighting, ultra-detailed 8k resolution, vertical 9:16 aspect ratio."
  ];

  window.PROMPTS_CEO = BASE_PROMPTS;
})();