// =========================================================================
// JIWAS STUDIO — MASTER DATABASE AI & DIGITAL ACCOUNT (database.js V3.1)
// Terintegrasi Penuh API H2H INCA STORE & JIWAS Backend Gateway
// =========================================================================

const DATABASE_AI_ACCOUNT = [
  // ==================== KATEGORI: AI & SMART TOOLS ====================
  {
    id: "ai-gemini",
    nama: "Google Gemini Advanced AI",
    kategori: "AI",
    subKategori: "Multimodal AI",
    logo: "images/canvas/gemini.jpg",
    harga: 80000,
    hargaPromo: 35000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login / Shared",
    garansi: "Garansi Sesuai Durasi",
    deskripsi: "Akses Gemini 1.5 Pro memori besar untuk analisa dokumen panjang, koding, dan pembuatan konten otomatis.",
    faq: [{ q: "Apakah instan?", a: "Ya, akun langsung dikirim seketika setelah pembayaran sukses." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "AI-GEMINI" },
    apiConfig: { productId: "AI GEMINI", variant: "Default" }
  },
  {
    id: "chatgpt",
    nama: "ChatGPT Plus GPT-4o",
    kategori: "AI",
    subKategori: "Text & Coding",
    logo: "images/canvas/gpt.jpg",
    harga: 95000,
    hargaPromo: 45000,
    badge: "🔥 POPULER",
    status: "ready",
    jenisAkun: "Shared Account Private",
    garansi: "30 Hari Replace",
    deskripsi: "Akses GPT-4o, pembuatan gambar DALL-E 3, analisa data, dan Custom GPTs resmi.",
    faq: [{ q: "Bisa untuk riset?", a: "Sangat direkomendasikan untuk koding, skripsi, dan penulisan naskah." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "CHATGPT" },
    apiConfig: { productId: "CHATGPT", variant: "Default" }
  },

  // ==================== KATEGORI: DESAIN, EDITING & KREATIF ====================
  {
    id: "canva-pro",
    nama: "Canva Pro Desain Suite",
    kategori: "Design",
    subKategori: "Graphic Design",
    logo: "images/canvas/canva.jpg",
    harga: 35000,
    hargaPromo: 15000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Invite Tim / Direct Login",
    garansi: "Full Garansi",
    deskripsi: "Akses jutaan elemen premium, foto studio, penghapus background instan, dan brand kit Canva Pro.",
    faq: [{ q: "Desain lama aman?", a: "Sangat aman, cukup gabung tim tanpa mengubah aset pribadi." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "CANVA-PRO" },
    apiConfig: { productId: "CANVA PRO", variant: "Default" }
  },
  {
    id: "capcut-pro",
    nama: "CapCut Pro Full Feature",
    kategori: "Video",
    subKategori: "Video Editing",
    logo: "images/canvas/capcut.jpg",
    harga: 30000,
    hargaPromo: 12000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login (PC & HP)",
    garansi: "Full Garansi",
    deskripsi: "Unlock semua efek transisi, AI auto-caption bahasa Indonesia, dan ekspor tanpa watermark.",
    faq: [{ q: "Bisa di laptop?", a: "Mendukung Windows, Mac, Android, dan iOS." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "CAPCUT-PRO" },
    apiConfig: { productId: "CAPCUT PRO", variant: "Default" }
  },
  {
    id: "capcut-basic",
    nama: "CapCut Basic Hemat",
    kategori: "Video",
    subKategori: "Video Editing",
   logo: "images/canvas/capcut.jpg",
    harga: 15000,
    hargaPromo: 5000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Akun",
    garansi: "Garansi Aktif",
    deskripsi: "Pilihan paling hemat untuk membuka fitur penting editing video TikTok & Reels.",
    faq: [{ q: "Bisa langsung pakai?", a: "Data akun terkirim otomatis detik ini juga." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "CAPCUT-BASIC" },
    apiConfig: { productId: "CAPCUT BASIC", variant: "Default" }
  },
  {
    id: "alightmotion",
    nama: "Alight Motion Pro",
    kategori: "Video",
    subKategori: "Motion Graphics",
    logo: "images/canvas/motion.jpg",
    harga: 25000,
    hargaPromo: 10000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login",
    garansi: "Full Garansi",
    deskripsi: "Buka preset XML, efek motion grafis, dan ekspor video resolusi tinggi tanpa watermark.",
    faq: [{ q: "Support preset 5MB?", a: "Ya, mendukung impor preset besar." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "ALIGHTMOTION" },
    apiConfig: { productId: "ALIGHTMOTION", variant: "Default" }
  },
  {
    id: "remini",
    nama: "Remini AI Photo Enhancer",
    kategori: "Design",
    subKategori: "AI Retouch",
    logo: "images/canvas/remini2.jpg",
    harga: 40000,
    hargaPromo: 18000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login",
    garansi: "Full Garansi",
    deskripsi: "Pertajam foto buram, tingkatkan resolusi wajah hingga HD micro-detail dalam 1 ketukan.",
    faq: [{ q: "Bisa untuk foto lama?", a: "Bisa, sangat cocok untuk restorasi foto jadul atau buram." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "REMINI" },
    apiConfig: { productId: "REMINI", variant: "Default" }
  },
  {
    id: "meitu",
    nama: "Meitu VIP Makeup & Filter",
    kategori: "Design",
    subKategori: "Beauty Retouch",
    logo: "images/canvas/meitu.jpg",
    harga: 35000,
    hargaPromo: 15000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login",
    garansi: "Full Garansi",
    deskripsi: "Akses seluruh filter estetika, AI makeup studio, dan body reshape VIP Meitu.",
    faq: [{ q: "Untuk iOS & Android?", a: "Bisa digunakan di smartphone Android maupun iPhone." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "MEITU" },
    apiConfig: { productId: "MEITU", variant: "Default" }
  },
  {
    id: "wink",
    nama: "Wink VIP+ Video Retouch",
    kategori: "Video",
    subKategori: "Video Retouch",
    logo: "images/canvas/wink.jpg",
    harga: 45000,
    hargaPromo: 20000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login VIP+",
    garansi: "Full Garansi",
    deskripsi: "Tingkatkan kualitas video wajah hingga 4K, hilangkan kerutan pada video, dan AI beauty cinematic.",
    faq: [{ q: "Support 4K?", a: "Ya, mendukung export video kualitas super jernih." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "WINK-VIP" },
    apiConfig: { productId: "WINK VIP+", variant: "Default" }
  },

  // ==================== KATEGORI: STREAMING & MUSIK ====================
  {
    id: "netflix",
    nama: "Netflix Premium UHD 4K",
    kategori: "Produktivitas",
    subKategori: "Streaming Film",
    logo: "images/canvas/neflix.jpg",
    harga: 50000,
    hargaPromo: 28000,
    badge: "🎬 4K UHD",
    status: "ready",
    jenisAkun: "Akun Sharing / Private Profil",
    garansi: "Anti Hold Garansi",
    deskripsi: "Nonton film dan series Netflix kualitas 4K HDR tanpa hambatan di Smart TV, HP, atau Laptop.",
    faq: [{ q: "Bisa di Smart TV?", a: "Bisa, tinggal login email dan password yang diberikan." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "NETFLIX" },
    apiConfig: { productId: "NETFLIX", variant: "Default" }
  },
  {
    id: "youtube-premium",
    nama: "YouTube Premium & Music",
    kategori: "Produktivitas",
    subKategori: "Streaming Bebas Iklan",
    logo: "images/canvas/youtube.jpg",
    harga: 30000,
    hargaPromo: 12000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct / Invite Keluarga",
    garansi: "Full Garansi",
    deskripsi: "Bebas iklan, putar di latar belakang layar mati, dan akses jutaan lagu di YouTube Music.",
    faq: [{ q: "Bisa pakai akun sendiri?", a: "Tergantung stok sistem saat checkout." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "YOUTUBE-PREM" },
    apiConfig: { productId: "YOUTUBE PREMIUM", variant: "Default" }
  },
  {
    id: "spotify",
    nama: "Spotify Premium Individual",
    kategori: "Produktivitas",
    subKategori: "Audio Streaming",
    logo: "images/canvas/vision.jpg",
    harga: 40000,
    hargaPromo: 18000,
    badge: "🎧 HI-RES",
    status: "ready",
    jenisAkun: "Direct Login",
    garansi: "Full Garansi",
    deskripsi: "Dengarkan musik tanpa jeda iklan, skip tanpa batas, dan unduh lagu offline.",
    faq: [{ q: "Bisa download lagu?", a: "Bisa didengarkan saat offline tanpa kuota." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "SPOTIFY-PREM" },
    apiConfig: { productId: "SPOTIFY PREMIUM", variant: "Default" }
  },
  {
    id: "apple-music",
    nama: "Apple Music Lossless",
    kategori: "Produktivitas",
    subKategori: "Audio Streaming",
    logo: "images/canvas/music.jpg",
    harga: 35000,
    hargaPromo: 15000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Invite / Direct",
    garansi: "Full Garansi",
    deskripsi: "Audio spasial Dolby Atmos dan kualitas audio lossless tanpa kompresi.",
    faq: [{ q: "Bisa untuk Android?", a: "Bisa diinstal di aplikasi Apple Music Android." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "APPLE-MUSIC" },
    apiConfig: { productId: "APPLE MUSIC", variant: "Default" }
  },
  {
    id: "vidio",
    nama: "Vidio Platinum",
    kategori: "Produktivitas",
    subKategori: "Streaming Sports & Drama",
    logo: "images/canvas/video.jpg",
    harga: 45000,
    hargaPromo: 22000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login",
    garansi: "Full Garansi",
    deskripsi: "Nonton tayangan olahraga live, sinetron, serial orisinal Vidio, dan film bioskop Indonesia.",
    faq: [{ q: "Bisa nonton bola?", a: "Mencakup tayangan live match sesuai paket Vidio Platinum." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "VIDIO" },
    apiConfig: { productId: "VIDIO", variant: "Default" }
  },
  {
    id: "viu",
    nama: "Viu Premium (Drakor)",
    kategori: "Produktivitas",
    subKategori: "Asian Drama",
    logo: "images/canvas/viu.jpg",
    harga: 25000,
    hargaPromo: 10000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Akun Instan",
    garansi: "Full Garansi",
    deskripsi: "Streaming serial drama Korea, anime, dan variety show Asia dengan subtitle Indonesia tercepat.",
    faq: [{ q: "Bebas iklan?", a: "Ya, bebas jeda iklan seluruh tayangan." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "VIU-PREM" },
    apiConfig: { productId: "VIU PREMIUM", variant: "Default" }
  },
  {
    id: "bstation",
    nama: "Bstation (Bilibili) Premium",
    kategori: "Produktivitas",
    subKategori: "Anime HD",
    logo: "images/canvas/cover.jpg",
    harga: 25000,
    hargaPromo: 12000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Akun Instan",
    garansi: "Full Garansi",
    deskripsi: "Nonton anime favorit kualitas 1080p/4K tanpa batas dan bebas iklan.",
    faq: [{ q: "Resolusi video?", a: "Buka semua akses resolusi tertinggi hingga 4K." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "BSTATION" },
    apiConfig: { productId: "BSTATION", variant: "Default" }
  },
  {
    id: "wetv",
    nama: "WeTV VIP",
    kategori: "Produktivitas",
    subKategori: "Drama & Series",
    logo: "images/canvas/wetv.jpg",
    harga: 30000,
    hargaPromo: 14000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login",
    garansi: "Full Garansi",
    deskripsi: "Akses fast track drama China, series Indonesia viral, dan tayangan VIP sebelum umum.",
    faq: [{ q: "Episode VIP terbuka?", a: "Semua episode VIP bisa langsung ditonton." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "WETV" },
    apiConfig: { productId: "WE TV", variant: "Default" }
  },
  {
    id: "visionplus",
    nama: "Vision+ Premium",
    kategori: "Produktivitas",
    subKategori: "TV & Live Streaming",
    logo: "images/canvas/vi.jpg",
    harga: 30000,
    hargaPromo: 15000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login",
    garansi: "Full Garansi",
    deskripsi: "Channel TV nasional terlengkap, film box office, dan tayangan orisinal Vision+.",
    faq: [{ q: "Bisa nonton TV nasional?", a: "Bisa diakses dari HP, tablet, maupun browser." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "VISIONPLUS" },
    apiConfig: { productId: "VISION+", variant: "Default" }
  },

  // ==================== KATEGORI: TOOLS, VPN & EDUKASI ====================
  {
    id: "express-vpn",
    nama: "ExpressVPN Premium",
    kategori: "Produktivitas",
    subKategori: "Security & VPN",
    logo: "images/canvas/expressvpn.jpg",
    harga: 60000,
    hargaPromo: 25000,
    badge: "🔒 SECURE",
    status: "ready",
    jenisAkun: "Direct Login / Key",
    garansi: "Full Garansi",
    deskripsi: "Koneksi VPN super cepat kelas dunia untuk privasi, browsing aman, dan unblock situs.",
    faq: [{ q: "Bisa ganti negara?", a: "Tersedia server di lebih dari 90 negara." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "EXPRESS-VPN" },
    apiConfig: { productId: "EXPRESS VPN", variant: "Default" }
  },
  {
    id: "inca-hma-vpn",
    nama: "HMA VPN (HideMyAss)",
    kategori: "Produktivitas",
    subKategori: "Security & VPN",
    logo: "images/canvas/vpn.jpg",
    harga: 45000,
    hargaPromo: 20000,
    badge: "🔒 SECURE",
    status: "ready",
    jenisAkun: "Direct Login",
    garansi: "Full Garansi",
    deskripsi: "VPN handal dengan cakupan ribuan lokasi IP untuk enkripsi koneksi data internet.",
    faq: [{ q: "Bisa di HP?", a: "Bisa diinstal di Android, iOS, maupun PC." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "HMA-VPN" },
    apiConfig: { productId: "HMA VPN", variant: "Default" }
  },
  {
    id: "zoom-pro",
    nama: "Zoom Pro Meeting",
    kategori: "Produktivitas",
    subKategori: "Video Conference",
    logo: "images/canvas/zoom.jpg",
    harga: 50000,
    hargaPromo: 25000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Direct Login / Lisensi",
    garansi: "Full Garansi",
    deskripsi: "Meeting online tanpa batas durasi 40 menit, kapasitas 100 peserta, dan rekaman cloud.",
    faq: [{ q: "Bisa meeting seharian?", a: "Durasi meeting hingga 30 jam nonstop." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "ZOOM" },
    apiConfig: { productId: "ZOOM", variant: "Default" }
  },
  {
    id: "duolingo",
    nama: "Duolingo Super (Plus)",
    kategori: "Produktivitas",
    subKategori: "Belajar Bahasa",
    logo: "images/canvas/duo.jpg",
    harga: 35000,
    hargaPromo: 15000,
    badge: "⚡ AUTO BOT",
    status: "ready",
    jenisAkun: "Invite / Direct",
    garansi: "Full Garansi",
    deskripsi: "Belajar bahasa asing tanpa batasan hati (nyawa tak terbatas) dan tanpa gangguan iklan.",
    faq: [{ q: "Progres belajar aman?", a: "Aman, progres akun Anda tetap berlanjut seperti biasa." }],
    supplier: { supplierId: "INCA_STORE", internalCode: "DUOLINGO" },
    apiConfig: { productId: "DUOLINGO", variant: "Default" }
  }
];