// =========================================================================
// JIWAS STUDIO - DYNAMIC REGISTRY (data.js V2.7)
// Master Dataset Registry: Foto Studio AI, Video Sinematik, UMKM, & Retouch
// =========================================================================

window.KATALOG_REGISTRY = [
  // --- FOTO STUDIO AI (LIVE) ---
  {
    id: "velvet-lux",
    title: "Luxury Royal Velvet Studio",
    folder: "velvet",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_VELVET",
    scriptUrl: "prompts/velvet.js",
    rating: "4.9/5",
    sales: "150+ Terjual"
  },
  {
    id: "hijab-lux",
    title: "Luxury Hijab Collection",
    folder: "hijab",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_HIJAB",
    scriptUrl: "prompts/hijab.js",
    rating: "4.9/5",
    sales: "120+ Terjual"
  },
  {
    id: "couple-cinematic",
    title: "Luxury Couple Cinematic",
    folder: "couple",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_COUPLE",
    scriptUrl: "prompts/couple.js",
    rating: "5.0/5",
    sales: "90+ Terjual"
  },
  {
    id: "family-lux",
    title: "Luxury Family Collection",
    folder: "family",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_FAMILY",
    scriptUrl: "prompts/family.js",
    rating: "5.0/5",
    sales: "200+ Terjual"
  },
  {
    id: "family02-lux",
    title: "Luxury Family Collection Vol.02",
    folder: "family02",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_FAMILY02",
    scriptUrl: "prompts/family02.js",
    rating: "4.9/5",
    sales: "85+ Terjual"
  },
  {
    id: "family03-lux",
    title: "Luxury Family Collection Vol.03",
    folder: "family03",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_FAMILY03",
    scriptUrl: "prompts/family03.js",
    rating: "4.8/5",
    sales: "70+ Terjual"
  },
  {
    id: "ceo-lux",
    title: "Luxury CEO & Corporate Executive",
    folder: "ceo",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_CEO",
    scriptUrl: "prompts/ceo.js",
    rating: "4.9/5",
    sales: "110+ Terjual"
  },
  {
    id: "fantasi-gold",
    title: "Luxury Fantasy Gold",
    folder: "fantasi",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_FANTASI",
    scriptUrl: "prompts/fantasi.js",
    rating: "4.8/5",
    sales: "65+ Terjual"
  },
  {
    id: "makeup-glam",
    title: "Luxury Beauty & Makeover",
    folder: "makeup",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_MAKEUP",
    scriptUrl: "prompts/makeup.js",
    rating: "4.9/5",
    sales: "95+ Terjual"
  },
  {
    id: "lifestyle-lux",
    title: "Luxury Urban Lifestyle",
    folder: "lifestyle",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_LIFESTYLE",
    scriptUrl: "prompts/lifestyle.js",
    rating: "4.7/5",
    sales: "50+ Terjual"
  },
  {
    id: "girlies-style",
    title: "Luxury Girlies & Style",
    folder: "girlies",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_GIRLIES",
    scriptUrl: "prompts/girlies.js",
    rating: "4.9/5",
    sales: "130+ Terjual"
  },
  {
    id: "makeover-glam",
    title: "Luxury Makeover & Glam",
    folder: "makeover",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_MAKEOVER",
    scriptUrl: "prompts/makeover.js",
    rating: "4.8/5",
    sales: "80+ Terjual"
  },
  {
    id: "ladys-chic",
    title: "Luxury Ladys Chic",
    folder: "ladys",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_LADYS",
    scriptUrl: "prompts/ladys.js",
    rating: "4.9/5",
    sales: "90+ Terjual"
  },
{
  id: "family-cloud36",
  folder: "family36",
  title: "The Dreamy Cloud Royal Family Collection",
  category: "Foto AI",
  type: "foto",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_FAMILY36",
  scriptUrl: "prompts/family36.js",
  coverUrl: "images/family36/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "36 formula potret atelier keluarga bangsawan berlatar instalasi lampion awan bercahaya, kemilau lampu peri, serta busana sutra satin berornamen bulu mewah dalam rasio 9:16."
},
{
  id: "family-heritage36",
  folder: "family-heritage36",
  title: "The Noble Heritage & Modern Hijab Family",
  category: "Foto AI",
  type: "foto",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_FAMILY_HERITAGE36",
  scriptUrl: "prompts/family-heritage36.js",
  coverUrl: "images/family-heritage36/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "36 formula potret atelier keluarga muslim modern dengan 3 variasi gaun mewah: Renda Chantilly Dusty Rose, Sulam Perak Biru Malam, dan Wastra Tenun Nusantara."
},
{
  id: "family-casual36",
  folder: "family-casual36",
  title: "The Modern Casual & Mustard Harmony Family",
  category: "Foto AI",
  type: "foto",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_FAMILY_CASUAL36",
  scriptUrl: "prompts/family-casual36.js",
  coverUrl: "images/family-casual36/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "36 formula potret studio keluarga kasual modern dengan 2 gaya outfit segar: Jaket Denim Biru Muda di studio peach pastel dan Kemeja Mustard Ochre di studio berpanel kayu modern."
},

{
  id: "family-celestial36",
  folder: "family-celestial36",
  title: "The Celestial Glamour Family Collection",
  category: "Foto AI",
  type: "foto",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_FAMILY_CELESTIAL36",
  scriptUrl: "prompts/family-celestial36.js",
  coverUrl: "images/family-celestial36/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "36 formula potret atelier Korea royal glamour keluarga bertiga dalam 3 busana satin sutra mewah berhias aksen bulu, cloud lighting, dan dekorasi pampas emas 8K 9:16."
},


  // --- PRE-LAUNCH TEASER PACKS (TEASER) ---
  {
    id: "umkm-commercial",
    title: "Commercial UMKM & Product Studio",
    folder: "umkm",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_UMKM",
    scriptUrl: "prompts/umkm.js",
    releaseDate: "Segera Hadir",
    description: "Katalog 100 prompt foto komersial produk makanan, minuman, skincare, dan packaging mewah."
  },
  {
    id: "sekolah-yearbook",
    title: "Yearbook & Formal Identity Studio",
    folder: "sekolah",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_SEKOLAH",
    scriptUrl: "prompts/sekolah.js",
    releaseDate: "Segera Hadir",
    description: "100 Formula foto wisuda, buku tahunan sekolah, pasfoto dinas, dan portofolio akademis."
  },
  {
    id: "retouch-restoration",
    title: "ID Photo & Beauty Restoration",
    folder: "retouch",
    category: "Foto AI",
    type: "foto",
    status: "live",
    promptVarName: "PROMPTS_RETOUCH",
    scriptUrl: "prompts/retouch.js",
    releaseDate: "Segera Hadir",
    description: "Formula retouching wajah realistis, pemulihan foto buram, dan skin texture micro-detail."
  },

  // --- VIDEO AI (LIVE) ---
  {
    id: "video-cinematic",
    title: "KUMPULAN VIDEO REQUESS",
    folder: "video",
    category: "Video AI",
    type: "video",
    status: "live",
    promptVarName: "PROMPTS_VIDEO",
    scriptUrl: "prompts/video.js",
    rating: "Silakan pesan yang di butuhkan, paket : 36 prompt video",
    sales: "180+ Terjual"
  },

  // --- AKUN AI & DIGITAL TOOLS (LIVE) ---
  {
    id: "chatgpt-plus",
    title: "ChatGPT Plus Shared / Private",
    folder: "canvas",
    category: "Akun AI",
    type: "digital",
    status: "live",
    priceText: "Rp35.000",
    description: "Akses ChatGPT-4o & Canvas resmi tanpa batas untuk pembuatan konten dan riset."
  },
  {
    id: "midjourney-pro",
    title: "Midjourney Fast Hours Access",
    folder: "canvas",
    category: "Akun AI",
    type: "digital",
    status: "live",
    priceText: "Rp45.000",
    description: "Akses image generator Midjourney kualitas fotorealistik dengan kuota fast hours melimpah."
  },
  {
    id: "canva-pro",
    title: "Canva Pro Desain Suite",
    folder: "canvas",
    category: "Akun AI",
    type: "digital",
    status: "live",
    priceText: "Rp15.000",
    description: "Akun Canva Pro Lifetime invite untuk template premium dan hapus background instan."
  },
{
    id: "zen-relaxation",
    title: "Zen & Shinkai Serenity 9:16",
    folder: "zen-relaxation",
    category: "Video AI",
    type: "video",
    status: "live",
    totalItems: 36,
    promptVarName: "PROMPTS_ZEN_RELAXATION",
    scriptUrl: "prompts/videos/zen-relaxation.js",
    coverUrl: "videos/zen-relaxation/cover.mp4",
    rating: "5.0/5",
    sales: "Baru Rilis",
    description: "36 Formula video sinematik relaksasi vertikal 9:16 bergaya anime Makoto Shinkai fotorealistik 8K HDR."
  },
{
    id: "nature-cinematic",
    title: "Nature & Forest Cinematic 9:16",
    folder: "nature-cinematic",
    category: "Video AI",
    type: "video",
    status: "live",
    totalItems: 36,
    promptVarName: "PROMPTS_NATURE_CINEMATIC",
    scriptUrl: "prompts/videos/nature-cinematic.js",
    coverUrl: "videos/nature-cinematic/cover.mp4",
    rating: "5.0/5",
    sales: "Baru Rilis",
    description: "36 Formula video sinematik alam vertikal 9:16: terowongan pohon kanopi, danau cermin, dan hutan purba 8K HDR."
  },
{
  id: "slow-natural",
  title: "Slow Natural 9:16",
  folder: "slow-natural",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_SLOW_NATURAL",
  scriptUrl: "prompts/videos/slow-natural.js",
  coverUrl: "videos/slow-natural/cover.mp4",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Koleksi sinematik vertikal 9:16 perjalanan santai menembus lekuk jalan pesisir, tebing samudra, dan perbukitan hijau dengan visual bergaya Makoto Shinkai berpadu fotorealisme 8K berawan megah."
},
{
  id: "ninja-alone",
  title: "Ninja Alone 9:16",
  folder: "ninja-alone",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_NINJA_ALONE",
  scriptUrl: "prompts/videos/ninja-alone.js",
  coverUrl: "videos/ninja-alone/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Kisah sunyi seorang shinobi pengelana yang memikul beban sumpah darah, luka masa lalu, dan keheningan takdir. Visual puitis menembus hujan malam, guguran daun momiji beriak di air, serta keagungan alam yang menyapa kesendiriannya."
},
{
    id: "high-space",
    title: "High Space 9:16",
    folder: "high-space",
    category: "Video AI",
    type: "video",
    status: "live",
    totalItems: 36,
    promptVarName: "PROMPTS_high_space",
    scriptUrl: "prompts/videos/high-space.js",
    coverUrl: "videos/high-space/cover.jpg",
    rating: "4.0/3",
    sales: "Baru Rilis",
    description: "Eksplorasi sinematik vertikal menembus batas ruang dan waktu; memadukan fenomena gerhana matahari, ledakan nebula kosmik di pesisir sunyi, serta perenungan manusia di bawah cakrawala bintang tak terbatas."
  },
{
  id: "lonely-boy",
  title: "Autumn Solitude 9:16",
  folder: "lonely-boy",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_LONELY_BOY",
  scriptUrl: "prompts/videos/lonely-boy.js",
  coverUrl: "videos/lonely-boy/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Eksplorasi sinematik ketenangan jiwa dan kesendirian puitis di kabin tepi danau musim gugur. Perpaduan atmosfer magis Makoto Shinkai dengan realisme visual 8K IMAX, golden hour yang hangat, dan resonansi batin yang mendalam."
},
// Tambahkan objek ini ke dalam array KATALOG_REGISTRY di file data.js:
{
  id: "green-natural",
  title: "Green Natural Serenity 9:16",
  folder: "green-natural",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_GREEN_NATURAL",
  scriptUrl: "prompts/videos/green-natural.js",
  coverUrl: "videos/green-natural/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Perjalanan kontemplatif menembus lembah zamrud, tebing air terjun berkabut, danau cermin di bawah purnama megah, serta keteduhan pohon purba mistis dengan visual hiperrealistik 8K dan kedalaman atmosfer Shinkai."
},
{
  id: "romance-couple",
  title: "Romantic Serenity 9:16",
  folder: "romance-couple",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_ROMANCE_COUPLE",
  scriptUrl: "prompts/videos/romance-couple.js",
  coverUrl: "videos/romance-couple/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Koleksi sinematik momen intim sepasang kekasih di alam terbuka megah, padang bunga, danau pegunungan, dan panorama senja berkabut dengan kedalaman HDR dan ketenangan emosional."
},
{
  id: "beauty-village",
  title: "Beauty Village 9:16",
  folder: "beauty-village",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_BEAUTY_VILLAGE",
  scriptUrl: "prompts/videos/beauty-village.js",
  coverUrl: "videos/beauty-village/cover.jpg",
  rating: "3.0/3",
  sales: "Baru Rilis",
  description: "Eksplorasi sinematik vertikal kedamaian hidup desa: rumah panggung kayu beratap rumbia, tungku kayu berasap harum, gemercik sungai jernih berbatu, kebun sayur subur, serta harmoni keluarga sederhana berlatar perbukitan berkabut dan langit biru megah."
},
{
  id: "coastal-solitude",
  title: "Coastal Solitude 9:16",
  folder: "coastal-solitude",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_COASTAL_SOLITUDE",
  scriptUrl: "prompts/videos/coastal-solitude.js",
  coverUrl: "videos/coastal-solitude/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Koleksi 36 formula sinematik vertikal bertema jalan pesisir, tebing samudra, dan formasi awan kumulonimbus megah. Dirancang khusus untuk video relaksasi, Reels, dan TikTok dengan perpaduan keagungan visual Makoto Shinkai dan fotorealisme IMAX 8K."
},
{ 
  id: "umkm-commercial", 
  folder: "umkm", 
  title: "Commercial UMKM & Product Studio", 
  type: "product", 
  status: "live", 
  rating: "5.0/5", 
  sales: "3 Live + 10 On-Demand",
  scriptUrl: "prompts/umkm/commercial.js",
  promptVarName: "PROMPTS_UMKM_COMMERCIAL"
},
{
  id: "coastal-serenity",
  title: "Coastal Serenity 9:16",
  folder: "coastal-serenity",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_COASTAL_SERENITY",
  scriptUrl: "prompts/videos/coastal-serenity.js",
  coverUrl: "videos/coastal-serenity/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Perjalanan puitis dan hening menembus lekuk jalan pesisir samudra, tebing karang berlumut, padang rumput berangin, dan kanopi senja dengan kedalaman atmosfer Makoto Shinkai berpadu hiper-realisme sinematik 8K IMAX."
},
{
  id: "alam-indah",
  title: "Alam Indah 9:16",
  folder: "alam-indah",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_ALAM_INDAH",
  scriptUrl: "prompts/videos/alam-indah.js",
  coverUrl: "videos/alam-indah/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Eksplorasi visual hipnotik menembus lorong pepohonan rimbun, kanopi kanopi bunga merah flamboyan, terowongan hutan lumut basah, serta jalan pesisir beraspal licin di bawah kubah awan kumulonimbus dan langit kobalt mendalam yang memancarkan ketenangan batin mutlak."
},
// Tambahkan ke dalam array KATALOG_REGISTRY di data.js
{
  id: "transformasi-of-life",
  title: "Transformasi of Life 9:16",
  folder: "transformasi-of-life",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_TRANSFORMASI_OF_LIFE",
  scriptUrl: "prompts/videos/transformasi-of-life.js",
  coverUrl: "videos/transformasi-of-life/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Eksplorasi sinematik vertikal beresolusi 8K tentang katarsis manusia: metamorfosis dari lembah air mata, hutang, dan kemiskinan menuju puncak kelimpahan, martabat, dan sujud syukur dengan pencahayaan Makoto Shinkai atmospheric grandeur berpadu IMAX photorealism."
},

// Tambahkan entri ini ke dalam array KATALOG_REGISTRY
{
  id: "hujan-deras",
  title: "Memorial Tempest 9:16",
  folder: "hujan-deras",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_HUJAN_DERAS",
  scriptUrl: "prompts/videos/hujan-deras.js",
  coverUrl: "videos/hujan-deras/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Eksplorasi sinematik hujan lebat, terpaan angin badai, kilat atmosferik, dan lorong pedesaan basah yang memancarkan kenangan sunyi, mencekam sekaligus menenangkan jiwa secara mendalam."
},
// Tambahkan entri ini ke dalam array KATALOG_REGISTRY
{
  id: "dunia-fantasi",
  title: "Dunia Fantasi 9:16",
  folder: "dunia-fantasi",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_DUNIA_FANTASI",
  scriptUrl: "prompts/videos/dunia-fantasi.js",
  coverUrl: "videos/dunia-fantasi/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Eksplorasi megah pulau melayang di atas samudra awan, suaka bulan sabit surgawi, istana pagoda bercahaya magis, dan arsitektur dongeng vertikal yang membangkitkan rasa takjub, kedamaian batin, dan keajaiban mimpi."
},
// Tambahkan entri ini ke dalam array KATALOG_REGISTRY
{
  id: "romance",
  title: "Romance Sunset 9:16",
  folder: "romance",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_ROMANCE",
  scriptUrl: "prompts/videos/romance.js",
  coverUrl: "videos/romance/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Kompilasi sinematik vertikal 9:16 momen romansa sepasang kekasih di pesisir senja, siluet dermaga danau, padang ilalang berbisik, serta pelukan hangat di bawah cahaya matahari terbenam keemasan yang sarat kedamaian batin dan keintiman abadi."
},
// Tambahkan entri ini ke dalam array KATALOG_REGISTRY
{
  id: "romance-03",
  title: "Romance Autumn 9:16",
  folder: "romance-03",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_ROMANCE_03",
  scriptUrl: "prompts/videos/romance-03.js",
  coverUrl: "videos/romance-03/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Kompilasi sinematik vertikal 9:16 kehangatan cinta di musim gugur: langkah berpayung merah di atas trotoar basah berdaun maple, siluet di jembatan lengkung klasik berhias lentera temaram, serta momen tenang berdua menatap danau berkabut keemasan."
},
// Tambahkan entri ini ke dalam array KATALOG_REGISTRY
{
  id: "foto-90an",
  title: "Nostalgia 90an 9:16",
  folder: "foto-90an",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_FOTO_90AN",
  scriptUrl: "prompts/videos/foto-90an.js",
  coverUrl: "videos/foto-90an/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Dokumenter sinematik vertikal 9:16 suasana hangat pedesaan era 1990-an: pendar TV tabung jadul di atas tikar pandan, hembusan kipas angin meja klasik, gerobak gorengan tepi jalan berpelindung terpal, serta santap siang bersahaja di pematang sawah hijau yang memancarkan ketenangan batin, memori masa kecil, dan kedamaian jiwa."
},
// Tambahkan entri ini ke dalam array KATALOG_REGISTRY
{
  id: "mesin-tani",
  title: "Bio-Mecha Agritech 9:16",
  folder: "mesin-tani",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_MESIN_TANI",
  scriptUrl: "prompts/videos/mesin-tani.js",
  coverUrl: "videos/mesin-tani/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Eksplorasi sinematik vertikal 9:16 mesin-mesin tani bionik nan unik: traktor kumbang berkaki heksapoda, robot perontok padi berbahan bambu-uap, kincir mekanik hidrolik kayu, dan inovasi agrikultur futuristik yang memadukan kearifan tanah persawahan dengan keagungan teknologi organik."
},
// Tambahkan entri ini ke dalam array KATALOG_REGISTRY
{
  id: "pengendara-moster",
  title: "The Monster Rider 9:16",
  folder: "pengendara-moster",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_PENGENDARA_MOSTER",
  scriptUrl: "prompts/videos/pengendara-moster.js",
  coverUrl: "videos/pengendara-moster/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Epos sinematik vertikal 9:16 seorang wanita pemberani menunggangi makhluk purba raksasa, dinosaurus titan, elang angkasa, ular purba raksasa, hingga pohon raksasa purba yang berjalan melintasi lanskap alam nan megah dan menghipnotis jiwa."
},
// Tambahkan entri ini ke dalam array KATALOG_REGISTRY
{
  id: "tsunami",
  title: "Tsunami Megasurge 9:16",
  folder: "tsunami",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_TSUNAMI",
  scriptUrl: "prompts/videos/tsunami.js",
  coverUrl: "videos/tsunami/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Dokumentasi visual sinematik 9:16 gelombang megatsunami samudra, surutnya air laut pesisir, dinding air raksasa melampaui atap perkampungan nelayan, dan kedahsyatan alam bahari yang memicu rasa takjub emosional mendalam."
},
// Tambahkan entri ini ke dalam array KATALOG_REGISTRY
{
  id: "megatrust",
  title: "Megatrust 9:16",
  folder: "megatrust",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_MEGATRUST",
  scriptUrl: "prompts/videos/megatrust.js",
  coverUrl: "videos/megatrust/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Dokumentasi visual sinematik 9:16 pertarungan epik kapal-kapal titan samudra: kapal kontainer raksasa dengan peti kemas jatuh ke laut terpaan badai, kapal pesiar termewah dunia diterjang ombak rogue 30 meter, kapal tanker tenggelam separuh badan, dan keagungan laut lepas yang membangkitkan rasa takjub emosional mendalam."
},
{
  id: "coastal-horizon",
  title: "Coastal Horizon & Serene Cliffs 9:16",
  folder: "coastal-horizon",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_COASTAL_HORIZON",
  scriptUrl: "prompts/videos/coastal-horizon.js",
  coverUrl: "videos/coastal-horizon/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Eksplorasi sinematik lanskap pesisir megah, tebing samudra vertikal, dan aspal pesisir berkilau surya. Menggabungkan kemegahan atmosferik Makoto Shinkai dengan realisme optik IMAX 8K, HDR 1000-nits, dan resonansi batin mendalam."
},
{
  id: "divine-sanctuary",
  title: "Divine Sanctuary & Ocean Fury 9:16",
  folder: "divine-sanctuary",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_DIVINE_SANCTUARY",
  scriptUrl: "prompts/videos/divine-sanctuary.js",
  coverUrl: "videos/divine-sanctuary/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Kompilasi sinematik dramatis yang menggugah empati dan spiritualitas mendalam: keteguhan sujud di hadapan gelombang samudra, heroisme penyelamatan tanpa pamrih, keajaiban masjid suci di lautan puing, dan keagungan langit kobalt Shinkai berpadu fotorealisme 8K IMAX."
},

{
  id: "stik-samurai02",
  title: "Stick to Samurai Vol.02 9:16",
  folder: "stik-samurai02",
  category: "Video AI",
  type: "video",
  workflow: "frame-to-frame", // Flag sistem: memicu interface 3 kotak & 3 tombol salin di app.js
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_STIK_SAMURAI02",
  scriptUrl: "prompts/videos/stik-samurai02.js",
  coverUrl: "videos/stik-samurai02/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Koleksi transformasi artistik frame-to-frame Vol.02 POV tangan seniman dari sudut atas. Menampilkan evolusi garis kerangka lidi (stick figure) minimalis di atas kertas bertekstur menjadi ilustrasi sosok prajurit samurai manusia berzirah lengkap dengan pose katana legendaris dan goresan tinta hitam pekat (sumi-e)."
},
{
  id: "stik-samurai",
  title: "Stick to Samurai 9:16",
  folder: "stik-samurai",
  category: "Video AI",
  type: "video",
  workflow: "frame-to-frame",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_STIK_SAMURAI",
  scriptUrl: "prompts/videos/stik-samurai.js",
  coverUrl: "videos/stik-samurai/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Transformasi lakaran lidi mentah ringkas menjadi pahlawan samurai era feudal Jepun hiper-realistik 8K berarsir dakwat sumi-e, lengkap dengan zirah o-yoroi penuh dan kilauan pedang katana."
},
{
  id: "stick-pendekar",
  title: "Stick to Nusantara Warrior 9:16",
  folder: "stick-pendekar",
  theme: "Transformasi coretan garis lidi pencak silat menjadi pendekar pahlawan Nusantara hiper-realistis",
  totalItems: 36,
  workflow: "frame-to-frame",
  aspectRatio: "9:16"
},
// Tambahkan objek ini ke dalam array KATALOG_REGISTRY di data.js
{
  id: "alam-desa",
  title: "Alam Desa Sinematik 9:16",
  folder: "alam-desa",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_ALAM_DESA",
  scriptUrl: "prompts/videos/alam-desa.js",
  coverUrl: "videos/alam-desa/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Koleksi 36 formula video vertikal 9:16 suasana pedesaan asri nan damai. Menggabungkan kedalaman lanskap Shinkai dengan fotorealisme 8K IMAX, terasering hijau subur, sungai jernih, dan ketenangan jiwa tropis."
},
{
  id: "lahan-kebun",
  title: "Lahan ke Kebun Impian 9:16",
  folder: "lahan-kebun",
  category: "Video AI",
  type: "video",
  workflow: "frame-to-frame",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_LAHAN_KEBUN",
  scriptUrl: "prompts/videos/lahan-kebun.js",
  coverUrl: "videos/lahan-kebun/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Transformasi visual lahan tanah kosong gersang menjadi perkebunan organik mandiri, kolam ikan, kandang ayam, dan cottage kayu modern."
},
// Tambahkan objek ini ke dalam array KATALOG_REGISTRY di data.js:
{
  id: "puspa-rimba",
  title: "Puspa Rimba 9:16",
  folder: "puspa-rimba",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_PUSPA_RIMBA",
  scriptUrl: "prompts/videos/puspa-rimba.js",
  coverUrl: "videos/puspa-rimba/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Koleksi 36 video sinematik vertikal mikrokosmos peri hutan tropis nusantara berambut panjang melandai betis, menembus kabut lumut purba, kanopi bercahaya emas, dan ketenangan batin mendalam."
},
{
  id: "family-trio-capsule36",
  folder: "family-trio-capsule36",
  title: "The Trinity Capsule: 3-Wardrobe Family Collection",
  category: "Foto AI",
  type: "foto",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_FAMILY_TRIO_CAPSULE36",
  scriptUrl: "prompts/family-trio-capsule36.js",
  coverUrl: "images/family-trio-capsule36/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "36 formula potret atelier keluarga bertiga (ayah, ibu, balita) dalam 3 variasi outfit: Pastel Chic, Monokrom Bersih, dan Kasual Denim. Rasio 9:16 fotorealistik 8K."
},
{
  id: "cloud-treehouse-haven",
  title: "Cloud Treehouse Haven 9:16",
  folder: "cloud-treehouse-haven",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_CLOUD_TREEHOUSE_HAVEN",
  scriptUrl: "prompts/videos/cloud-treehouse-haven.js",
  coverUrl: "videos/cloud-treehouse-haven/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Eksplorasi sinematik desa rumah pohon purba di atas lautan awan. Visual puitis berpadu realisme IMAX 8K, jembatan kayu, lentera hangat, dan kedamaian batin tanpa batas."
},
{
  id: "celestial-arbor",
  title: "Celestial Arbor 9:16",
  folder: "celestial-arbor",
  category: "Video AI",
  type: "video",
  status: "live",
  totalItems: 36,
  promptVarName: "PROMPTS_CELESTIAL_ARBOR",
  scriptUrl: "prompts/videos/celestial-arbor.js",
  coverUrl: "videos/celestial-arbor/cover.jpg",
  rating: "5.0/5",
  sales: "Baru Rilis",
  description: "Eksplorasi sinematik perkampungan pohon surgawi di atas lautan awan, menampilkan kehidupan damai para peri berwajah Asia, jembatan gantung berlumut, dan air terjun kanopi dengan pencahayaan hangat keemasan."
}
];

// Backward Compatibility Aliases & Global Attachment
window.KATALOG_FOTO = window.KATALOG_REGISTRY.filter(item => item.type === "foto" && item.status === "live");
window.KATALOG_VIDEO = window.KATALOG_REGISTRY.filter(item => item.type === "video" && item.status === "live");
window.KATALOG_AKUN = window.KATALOG_REGISTRY.filter(item => item.type === "digital" && item.status === "live");

var KATALOG_FOTO = window.KATALOG_FOTO;
var KATALOG_VIDEO = window.KATALOG_VIDEO;
var KATALOG_AKUN = window.KATALOG_AKUN;